### PR TITLE
Feature/smaller depot

### PR DESCRIPTION
**Pull request by shuyao-guo**
- [x] Re-design ProcessType and EventType in eflips-depot and eflips-model when necessary. Enable shunting and correct standby arrival
- [x] Handle waiting correctly. Now waiting is **not** registered in the simulation core as a process
- [x] Enable shunting between areas in eflips-depot
- [x] Try around LINE Area and handling delayed schedules
- [x] Think about what kind of processes and areas are allowed and maybe add validation 
...?

### CODE REVIEW

**Comment by shuyao-guo** [comment]
Related to #120 

- [ ] improve documents
- [ ] fix tests 
- [ ] update eflips-model in pyproject.toml. Now the new release is not yet on pypi

**Comment by shuyao-guo** [comment]
> * [ ]  Re-design ProcessType and EventType in eflips-depot and eflips-model when necessary. Enable shunting and correct standby arrival
> 
>     * [x]  Handle waiting correctly. Now waiting is **not** registered in the simulation core as a process
> 
>     * [x]  Enable shunting between areas in eflips-depot
> 
>     * [ ]  Try around LINE Area and handling delayed schedules
> 
>     * [ ]  Think about what kind of processes and areas are allowed and maybe add validation
>       ...?

- ProcessType and EventType can stay unchanged. It is not necessary to distinguish from shunting and services. And standby is now used to represent a waiting event. related: https://github.com/mpm-tu-berlin/eflips-model/issues/61

**Comment by shuyao-guo** [comment]
Also the version number. I would say 3.3.0 or maybe even 4.0.0? Also we probably need to wait for a stable version of eflips-model

**Comment by ludgerheide** [comment]
Check #128 ebfore mergung.

**Comment by shuyao-guo** [comment]
#128 handled in https://github.com/mpm-tu-berlin/eflips-depot/pull/117/commits/7b147d10496216092758d336876c3deb4b6a0bf8

**Review by ludgerheide — APPROVED** [review]

**Pull request merged**
